=== nambach/XmlModules/src/main/resources/crawlRules/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://nambm.io/book"
           xmlns="http://nambm.io/book"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="book" type="bookType"/>

    <xs:complexType name="bookType">
        <xs:all>
            <xs:element type="notNullString" name="id"/>
            <xs:element type="notNullString" name="title"/>
            <xs:element type="xs:string" name="authors"/>
            <xs:element type="xs:string" name="image"/>
            <xs:element type="notNullString" name="link"/>
            <xs:element type="notNullString" name="price"/>
            <xs:element type="xs:string" name="oldPrice"/>
            <xs:element type="notNullString" name="status"/>
            <xs:element type="xs:string" name="siteName"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="notNullString">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== nambach/XmlModules/src/main/resources/book.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://nambm.io/book"
      xsi:schemaLocation="http://nambm.io/book ./crawlRules/book.xsd">
    <authors>Matsuda Michio</authors>
    <id>NSV_6198</id>
    <image>http://nhasachviet.vn//media/images/sach/bach-khoa-toan-thu-nuoi-day-tre-tap-2.jpg</image>
    <link>http://nhasachviet.vn/sach/combo-bach-khoa-toan-thu-nuoi-day-tre-bo-3-tap.html</link>
    <oldPrice>247.000đ</oldPrice>
    <price>210.000đ</price>
    <siteName>Nhà sách Việt</siteName>
    <status>true</status>
    <title>Combo Bách khoa toàn thư nuôi</title>
</book>
