=== nambach/XmlModules/src/main/resources/crawlRules/bookList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           targetNamespace="http://nambm.io/bookList"
           xmlns="http://nambm.io/bookList"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="books" type="bookList"/>

    <xs:complexType name="bookList">
        <xs:sequence>
            <xs:element name="book" type="bookType" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bookType">
        <xs:all>
            <xs:element type="notNullString" name="id"/>
            <xs:element type="notNullString" name="title"/>
            <xs:element type="xs:string" name="authors"/>
            <xs:element type="xs:string" name="image"/>
            <xs:element type="notNullString" name="link"/>
            <xs:element type="notNullString" name="price"/>
            <xs:element type="xs:string" name="oldPrice"/>
            <xs:element type="notNullString" name="status"/>
            <xs:element type="xs:string" name="siteName"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="notNullString">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse"/>
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== nambach/XmlModules/src/main/resources/bookList.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://nambm.io/bookList"
       xsi:schemaLocation="http://nambm.io/bookList ./crawlRules/bookList.xsd">
    <book>
        <authors>Matsuda Michio</authors>
        <id>NSV_6198</id>
        <image>http://nhasachviet.vn//media/images/sach/bach-khoa-toan-thu-nuoi-day-tre-tap-2.jpg</image>
        <link>http://nhasachviet.vn/sach/combo-bach-khoa-toan-thu-nuoi-day-tre-bo-3-tap.html</link>
        <oldPrice>247.000đ</oldPrice>
        <price>210.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Combo Bách khoa toàn thư nuôi</title>
    </book>
    <book>
        <authors>Tony Buổi Sáng</authors>
        <id>NSV_6195</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2017/ca-phe-cung-tony-tai-ban-2017.jpg</image>
        <link>http://nhasachviet.vn/sach/ca-phe-cung-tony-tai-ban-2017.html</link>
        <oldPrice>90.000đ</oldPrice>
        <price>76.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Cà phê cùng Tony - Tái bản</title>
    </book>
    <book>
        <authors>Seith M. Siegel</authors>
        <id>NSV_6022</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2017/con-duong-thoat-han.jpg</image>
        <link>http://nhasachviet.vn/sach/con-duong-thoat-han.html</link>
        <oldPrice>149.000đ</oldPrice>
        <price>126.650đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Con Đường Thoát Hạn</title>
    </book>
    <book>
        <authors>Sarah Khan -</authors>
        <id>NSV_5897</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/phat-trien-tu-duy-cho-hoc-sinh-tieu-hoc.jpg</image>
        <link>http://nhasachviet.vn/sach/combo-phat-trien-tu-duy-cho-hoc-sinh-tieu-hoc-bo-4-cuon.html</link>
        <oldPrice>260.000đ</oldPrice>
        <price>220.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Combo Phát triển tư duy cho</title>
    </book>
    <book>
        <authors>Glenn Doman,</authors>
        <id>NSV_5752</id>
        <image>http://nhasachviet.vn//media/images/sach/hinh-minh-hoa/dot_card_-_day_tre_hoc_toan_qc__1.jpg</image>
        <link>http://nhasachviet.vn/sach/dot-card-day-tre-hoc-toan-tap-2.html</link>
        <oldPrice>290.000đ</oldPrice>
        <price>261.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Dot card Dạy Trẻ Học Toán Tập</title>
    </book>
    <book>
        <authors>Carlo Collodi</authors>
        <id>NSV_5739</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/nhung-cuoc-phuu-luu-cua-pinocchio.jpg</image>
        <link>http://nhasachviet.vn/sach/nhung-cuoc-phuu-luu-cua-pinocchio.html</link>
        <oldPrice>120.000đ</oldPrice>
        <price>108.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Những cuộc phưu lưu của</title>
    </book>
    <book>
        <authors>Trương Yến</authors>
        <id>NSV_5723</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/combo-ma-van.jpg</image>
        <link>http://nhasachviet.vn/sach/combo-ma-van-giay-vai-triet-ly-song-cua-toi.html</link>
        <oldPrice>298.000đ</oldPrice>
        <price>238.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Combo Mã vân giày vải - Triết</title>
    </book>
    <book>
        <authors>Terry Chew</authors>
        <id>NSV_5619</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/combo-danh-thuc-tai-nang-toan-hoc.jpg</image>
        <link>http://nhasachviet.vn/sach/combo-danh-thuc-tai-nang-toan-hoc-tron-bo-05-cuon.html</link>
        <oldPrice>1.370.000đ</oldPrice>
        <price>1.164.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Combo đánh thức tài năng toán</title>
    </book>
    <book>
        <authors>Alexander Dumas</authors>
        <id>NSV_5579</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/ba-tuoc-mong-to-crixso.jpg</image>
        <link>http://nhasachviet.vn/sach/ba-tuoc-monte-cristo.html</link>
        <oldPrice>130.000đ</oldPrice>
        <price>110.500đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Bá Tước Monte Cristo</title>
    </book>
    <book>
        <authors>Nguyễn Mai Dung</authors>
        <id>NSV_5543</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/hong-nhan.jpg</image>
        <link>http://nhasachviet.vn/sach/hong-nhan.html</link>
        <oldPrice>79.000đ</oldPrice>
        <price>67.150đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Hồng Nhan</title>
    </book>
    <book>
        <authors>Douglas B. Holt</authors>
        <id>NSV_5538</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/hanh-trinh-bien-thuong-hieu-thanh-bieu-tuong.jpg</image>
        <link>http://nhasachviet.vn/sach/hanh-trinh-bien-thuong-hieu-thanh-bieu-tuong.html</link>
        <oldPrice>139.000đ</oldPrice>
        <price>118.150đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Hành Trình Biến Thương Hiệu</title>
    </book>
    <book>
        <authors>Thảo xù</authors>
        <id>NSV_5535</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/chi-can-mot-nguoi-hieu-em-trong-doi1.jpg</image>
        <link>http://nhasachviet.vn/sach/chi-can-mot-nguoi-hieu-em-trong-doi.html</link>
        <oldPrice>78.000đ</oldPrice>
        <price>66.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Chỉ Cần Một Người Hiểu Em</title>
    </book>
    <book>
        <authors>Brad Stone</authors>
        <id>NSV_5522</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/amazon.jpg</image>
        <link>http://nhasachviet.vn/sach/jeff-bezos-va-ky-nguyen-amazon.html</link>
        <oldPrice>102.000đ</oldPrice>
        <price>86.700đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Jeff Bezos Và Kỷ Nguyên Amazon</title>
    </book>
    <book>
        <authors>Lỗ Võ Bảo Lâm</authors>
        <id>NSV_5473</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/nang-thao-moc.jpg</image>
        <link>http://nhasachviet.vn/sach/i-love-cookbook-nang-thao-moc.html</link>
        <oldPrice>225.000đ</oldPrice>
        <price>191.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>I Love Cookbook - Nắng thảo</title>
    </book>
    <book>
        <authors>Frances Hodgson</authors>
        <id>NSV_5435</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2017/khu-vuon-bi-mat.jpg</image>
        <link>http://nhasachviet.vn/sach/khu-vuon-bi-mat.html</link>
        <oldPrice>75.000đ</oldPrice>
        <price>64.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Khu vườn bí mật</title>
    </book>
    <book>
        <authors>Nhiều Tác giả</authors>
        <id>NSV_5381</id>
        <image>http://nhasachviet.vn//media/images/Banner%20slideshow/vua-ban-le.jpg</image>
        <link>http://nhasachviet.vn/sach/bo-vua-ban-le-gom-3-cuon-sam-walton-cuoc-doi-kinh-doanh-tai-my-marketing-cho-ban-le-vua-ban-le-1cd.html</link>
        <oldPrice>468.000đ</oldPrice>
        <price>421.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Bộ Vua Bán Lẻ (Gồm 3 Cuốn :</title>
    </book>
    <book>
        <authors>Tờ Pi</authors>
        <id>NSV_5350</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/tam-biet-em-on.jpg</image>
        <link>http://nhasachviet.vn/sach/tam-biet-em-on.html</link>
        <oldPrice>86.000đ</oldPrice>
        <price>73.100đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Tạm biệt, em ổn</title>
    </book>
    <book>
        <authors>Đỗ Nhật Nam</authors>
        <id>NSV_5339</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/duong-xa-con-hat.jpg</image>
        <link>http://nhasachviet.vn/sach/duong-xa-con-hat.html</link>
        <oldPrice>73.000đ</oldPrice>
        <price>66.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Đường xa con hát</title>
    </book>
    <book>
        <authors>Đinh Hằng</authors>
        <id>NSV_5268</id>
        <image>http://nhasachviet.vn//media/images/Banner%20slideshow/qua-tre-de-chet(1).jpg</image>
        <link>http://nhasachviet.vn/sach/qua-tre-de-chet-hanh-trinh-nuoc-my.html</link>
        <oldPrice>65.000đ</oldPrice>
        <price>59.000đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Quá trẻ để chết - hành trình</title>
    </book>
    <book>
        <authors>Shin Yee Jin</authors>
        <id>NSV_5207</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/cha-me-thoi-dai-ky-thuat-so.jpg</image>
        <link>http://nhasachviet.vn/sach/cha-me-thoi-dai-ki-thuat-so.html</link>
        <oldPrice>109.000đ</oldPrice>
        <price>92.700đ</price>
        <siteName>Nhà sách Việt</siteName>
        <status>true</status>
        <title>Cha mẹ thời đại kĩ thuật số</title>
    </book>
    <book>
        <authors>Alex Ferguson</authors>
        <id>NSV_5185</id>
        <image>http://nhasachviet.vn//media/images/sach/File-anh-2015/hoi-ky-alexferguson.jpg</image>
        <link>http://nhasachviet.vn/sach/hoi-ky-alex-ferguson.html</link>
        <oldPrice>155.000đ</oldPrice>
